spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
      username: hexlet@example.com
      password: qwerty
      url: "jdbc:h2:./database"

  h2:
    console:
      enabled: true
      # Указываем путь, по которому будет открываться консоль
      path: /h2console/
      settings:
        web-allow-others: true
