spring:
  datasource:
      url: "jdbc:h2:./database"
      username: hexlet@example.com
      password: qwerty


  h2:
    console:
      enabled: true
      # Указываем путь, по которому будет открываться консоль
      path: /h2console/
      settings:
        web-allow-others: true
